databases:
  - name: smart-task-db
    databaseName: smart_task
    user: smart_user

services:
  - type: web
    name: smart-task-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd core && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-task-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.0
